### ISSUE TITLE
Renamer does not sorten filename when longer than windows path limit

### ISSUE THREAD

**Issue by HalfBakedHotdog** [Mik1ll/ScriptRenamer#1]
## System Info:
- Windows 10 Pro Version 21H1 64bit
- Shoko Server Daily (2021-08-26)
- Shoko Desktop Daily (2021-08-26)
- ScriptRenamer v1.7.2 (latest)

## Description:
If the folder structure & filename are more than 260 characters, the renamer should trim the rest of the filename.
Windows tends to get weird when files are over the 260 character path limit

## Steps to Reproduce: 

- Add a file to renamer
- Use default script (https://github.com/Mik1ll/ScriptRenamer#sample-script)
- Include "add '00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
- Filename is not shortened

**Comment by HalfBakedHotdog** [comment]
What I consider an ideal solution to this issue is the way Sonarr does it:
When the file's path exceeds 260 characters it shortens the file's episode's title (if included)

For example,
too\long\path to file\\[...]\Very Long Series Name\\[Group] Very Long Series Name 03 - Long Episode Title [720p x264 10bit].mkv

Would become
too\long\path to file\\[...]\Very Long Series Name\\[Group] Very Long Series Name 03 - Long Ep... [720p x264 10bit].mkv

If the filename is still too long it should remove the last characters of the filename

**Comment by Mik1ll** [comment]
Thanks for the suggestion, I will look into this soon. I'll probably put a flag for enabling/disabling truncating or allow references to the entire filename in expressions. Currently the workaround is to use `trunc(EpisodeTitleRomaji, 50)` for example.

**Comment by Mik1ll** [comment]
Unfortunately the way the renamer is designed makes it impractical to selectively shorten parts such as episode title without another parsing pass. Same goes for shortening based on full path length.
Though I have pushed a change in [v2.0.0](https://github.com/Mik1ll/ScriptRenamer/releases/tag/v2.0.0) to allow referencing the currently building filename/subfolder.
Something like this should work for most people:
```
add trunc(EpisodeTitleEnglish, 35);
        if (len(EpisodeTitleEnglish) > 35)
            add '...';
// ... other stuff ...
filename set trunc(Filename, 120); // Hard limit on file name size
subfolder set trunc(AnimeTitle, 30); // Hard limit on subfolder size, remember only to truncate each level if using multiple subfolder levels.
```
